//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_CoffeeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class remainingItem
    {
        public int item_id { get; set; }
        public int quanity { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
