//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_CoffeeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPurchaseInfo
    {
        public int purchase_id { get; set; }
        public int ingredient_id { get; set; }
        public double quantity_per_unit { get; set; }
        public decimal purchase_price { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual SupplyPurchase SupplyPurchase { get; set; }
    }
}
